pipeline {
    agent { label 'main' }
    parameters {
        string(name: 'name_container', defaultValue: 'proyecto-qa', description: 'nombre del docker')
        string(name: 'name_image', defaultValue: 'iproyecto-qa', description: 'nombre de la imagen')
        string(name: 'tag_image', defaultValue: 'latest', description: 'etiqueta de la imagen')
        string(name: 'port_image', defaultValue: '81', description: 'puerto de la imagen')
    }

    environment {
        name_final = "${name_container}${tag_image}${port_image}"
    }

    stages {
        stage('stop/rm') {
            when {
                expression {
                    DOCKER_EXIST = sh(returnStdout: true, script: 'echo "docker ps -q --filter name=${name_final}"')
                    return DOCKER_EXIST != ''
                }
            }
            steps {
                script {
                    sh '''
                        docker stop ${name_final}
                    '''
                }
            }
        }

        stage('build') {
            steps {
                script {
                    sh '''
                    docker build . -t ${name_image}:${tag_image}
                    '''
                }
            }
        }

        stage('run') {
            steps {
                script {
                    sh '''
                        docker run -dtp ${port_image}:80 --name ${name_final} ${name_image}:${tag_image}
                    '''
                }
            }
        }
    }
}